excluded:
    - "Modules/logic-business/Tests/*"
    - "Modules/logic-ui/Tests/*"
    - "Modules/logic-api/Tests/*"
    - "Modules/feature-startup/Tests/*"
    - "Modules/logic-business/.build/*"
    - "Modules/logic-ui/Tests/.build/*"
    - "Modules/logic-api/Tests/.build/*"
    - "Modules/feature-startup/.build/*"


disabled_rules:
  - comment_spacing
  - identifier_name
  - cyclomatic_complexity
  - function_body_length
  - type_body_length
  - function_parameter_count
  - nesting
  - file_length

line_length: 300

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
